id: PE6EEF9F8
initial_creation_type: ocr
source_metadata:
  volumes:
    531d4137e51749d1aebe71a7b0b37f7f:
      base_file: v053.txt
      image_group_id: I1PD95898
      title: ཤེས་རབས་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་དོན་བསྡུས་སྒྲོན་མ།
      total_pages: 1381
      volume_number: 53
